config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  get 'loaderio-6740bbace59df2ad01bb669b65e8333e', controller: :loader_io, action: :verify

  resources :passwords, controller: 'clearance/passwords', only: %i(new create)
  resource :session, controller: 'clearance/sessions', only: %i(create) do
    resource :u2f, controller: 'u2f_sessions', only: %i(new create)
  end

  resources :users, controller: 'clearance/users', only: %i(create) do
    resource :password,
             controller: 'clearance/passwords',
             only: %i(create edit update)
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'
  get '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out_get'
  get '/sign_up' => 'clearance/users#new', as: 'sign_up'

  root 'home#index'

  get '/auth/:provider/callback' => 'sessions#create_from_omniauth'

  resources :artists, only: %i(new create index)
  resources :collections, only: %i(show edit update new create) do
    resources :pendants, only: %i(show)
  end

  resources :colors, only: %i(index show new create)

  namespace :my, module: :current_user do
    resources :pendants, only: %i(new create index show edit update) do
      resource :colors, only: %i(new create), controller: 'pendant_colors'
    end
    resources :pendant_records, only: %i(new create index)
    resources :fake_pendant_records, only: %i(new create)
    resources :artists, only: %i(index)

    resource :last_week_in_pendants, only: %i(show)

    resources :u2f_registrations, only: %i(new create)

    resource :settings, only: %i(show)
  end

  namespace :api do
    namespace :my, module: :current_user do
      resources :push_notification_subscriptions, only: %i(create)
      resource :pendant_record_status, only: %i(show)
    end
  end
end

app/models/collection.rb
# frozen_string_literal: true

class Collection < ApplicationRecord
  has_many :collection_owners
  has_many :owners, through: :collection_owners

  has_many :glass_art_pieces

  def owners_names
    owners.pluck(:name).join(' ')
  end
end

app/controllers/collections_controller.rb
# frozen_string_literal: true

class CollectionsController < ApplicationController
  before_action :require_login, only: %i(edit update new create)

  def show
    @collection = Collection.find(params[:id])
  end

  def new
    @collection = current_user.collections.new
  end

  def create
    Collection.transaction do
      @collection = Collection.new
      if @collection.update update_params
        @collection.owners << current_user
        redirect_to collection_path(@collection)
      else
        render :new
      end
    end
  end

  def edit
    @collection = current_user.collections.find(params[:id])
    render :new
  end

  def update
    @collection = current_user.collections.find(params[:id])
    if @collection.update update_params
      redirect_to collection_path(@collection)
    else
      render :new
    end
  end

  private

  def update_params
    params.require(:collection).permit(:name)
  end
end

app/views/collections/_pendant_row.html.erb
<tr>
  <td><%= link_to pendant.name, collection_pendant_path(@collection, pendant) %></td>
  <td><%= pendant.artist_name %></td>
  <td><%= pendant.pendant_records.count %></td>
</tr>

app/views/collections/new.html.erb
<%= simple_form_for @collection do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/collections/show.html.erb
<div class="pendants">

  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-3"><%= @collection.name %></h1>
      <% if @collection.owners_names.strip.present? %>
          <p class="lead">Owned By: <%= @collection.owners_names %></p>
      <% end %>
      <p class="lead">Total Number of Pendants: <%= @collection.glass_art_pieces.count %></p>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Artist Name</th>
        <th>Times Worn</th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: 'pendant_row', collection: @collection.glass_art_pieces, as: :pendant %>
      </tbody>
    </table>
  </div>
</div>